import { Hotel } from "../models/hotel.model.js";

const hotels = [
  // --- القديم ---
  {
    name: "فندق النخبة",
    city: "القاهرة",
    price: 100,
    rating: 4.5,
    distance: 2,
    images: ["/hotel.jpg", "/hotel2.jpg", "/hotel3.jpg"],
    description: "فندق فاخر في قلب القاهرة مع جميع الخدمات الحديثة.",
    rooms: 50,
    availableRooms: 10,
    services: [
      "♿ Accessibility",
      "👶 Babysitter",
      "⚡ Electric charging station 22kW",
      "💪 Gym",
      "🅿️ Parking",
      "🐾 Pets",
      "🏊 Pool",
      "🧖 Spa",
    ],
    cancellationPolicy: "يمكنك إلغاء الحجز قبل 24 ساعة من الوصول.",
    paymentPolicy: "يتم الدفع عند الوصول.",
    minimumAge: 18,
  },
  {
    name: "فندق البحر الأحمر",
    city: "الغردقة",
    price: 80,
    rating: 4,
    distance: 5,
    images: ["/hotel4.jpg", "/hotel5.jpg", "/hotel6.jpg"],
    description:
      "فندق جميل يطل على البحر الأحمر ويوفر العديد من الأنشطة البحرية.",
    rooms: 40,
    availableRooms: 5,
    services: [
      "⚡ Electric charging station 7kW",
      "💪 Gym",
      "🅿️ Parking",
      "🏊 Pool",
      "🧖 Spa",
    ],
    cancellationPolicy: "يجب إلغاء الحجز قبل 48 ساعة من الوصول.",
    paymentPolicy: "يتم الدفع مقدماً.",
    minimumAge: 16,
  },
  {
    name: "فندق الأهرامات",
    city: "الجيزة",
    price: 120,
    rating: 4.8,
    distance: 1.2,
    images: ["/hotel7.jpg", "/hotel8.jpg", "/hotel9.jpg"],
    description: "فندق فاخر بجوار الأهرامات مع إطلالة رائعة.",
    rooms: 60,
    availableRooms: 8,
    services: [
      "♿ Accessibility",
      "⚡ Electric charging station 50-150kW",
      "🐾 Pets",
      "🧖 Spa",
      "🅿️ Parking",
    ],
    cancellationPolicy: "يمكنك إلغاء الحجز قبل 72 ساعة من الوصول.",
    paymentPolicy: "يتم الدفع عند الوصول.",
    minimumAge: 18,
  },
  {
    name: "فندق البحرين",
    city: "شرم الشيخ",
    price: 140,
    rating: 5,
    distance: 3.5,
    images: ["/hotel10.jpg", "/hotel11.jpg", "/hotel12.jpg"],
    description: "منتجع فاخر في شرم الشيخ مع شاطئ خاص.",
    rooms: 80,
    availableRooms: 15,
    services: [
      "🚌 Shuttle",
      "⚡ Electric charging station 7kW",
      "💪 Gym",
      "🏊 Pool",
      "🧖 Spa",
    ],
    cancellationPolicy: "يمكنك إلغاء الحجز قبل 24 ساعة من الوصول.",
    paymentPolicy: "يتم الدفع مقدماً.",
    minimumAge: 18,
  },
  {
    name: "فندق الماس",
    city: "شرم الشيخ",
    price: 150,
    rating: 5,
    distance: 4,
    images: ["/hotel13.jpg", "/hotel14.jpg", "/hotel15.jpg"],
    description: "منتجع فاخر في شرم الشيخ مع شاطئ خاص.",
    rooms: 80,
    availableRooms: 15,
    services: [
      "⚡ Electric charging station 22kW",
      "🅿️ Parking",
      "🐾 Pets",
      "🏊 Pool",
      "🧖 Spa",
    ],
    cancellationPolicy: "يجب إلغاء الحجز قبل 48 ساعة من الوصول.",
    paymentPolicy: "يتم الدفع عند الوصول.",
    minimumAge: 18,
  },
  {
    name: "فندق الواحة",
    city: "الغردقة",
    price: 95,
    rating: 4.3,
    distance: 2.8,
    images: ["/hotel16.jpg", "/hotel17.jpg", "/hotel18.jpg"],
    description: "فندق ممتاز مع حمام سباحة ومنطقة استرخاء في الغردقة.",
    rooms: 40,
    availableRooms: 12,
    services: [
      "♿ Accessibility",
      "⚡ Electric charging station 7kW",
      "💪 Gym",
      "🏊 Pool",
      "🧖 Spa",
    ],
    cancellationPolicy: "يمكنك إلغاء الحجز قبل 24 ساعة من الوصول.",
    paymentPolicy: "يتم الدفع مقدماً.",
    minimumAge: 18,
  },

  // --- الجديد 1 → 20 ---
  {
    name: "فندق الكرنك",
    city: "القاهرة",
    price: 85,
    rating: 3.8,
    distance: 1.5,
    images: ["/newhotel1.jpg", "/newhotel2.jpg", "/newhotel3.jpg"],
    description: "فندق عصري في القاهرة بالقرب من وسط المدينة.",
    rooms: 32,
    availableRooms: 6,
    services: ["🅿️ Parking", "🏊 Pool", "💪 Gym", "🐾 Pets", "⚡ Electric charging station 7kW"],
    cancellationPolicy: "يمكنك إلغاء الحجز قبل 48 ساعة من الوصول.",
    paymentPolicy: "يتم الدفع مقدماً.",
    minimumAge: 18,
  },
  {
    name: "فندق المتوسط",
    city: "الإسكندرية",
    price: 90,
    rating: 4.1,
    distance: 2,
    images: ["/newhotel4.jpg", "/newhotel5.jpg", "/newhotel6.jpg"],
    description: "فندق بإطلالة على البحر المتوسط في الإسكندرية.",
    rooms: 34,
    availableRooms: 7,
    services: ["🅿️ Parking", "🏊 Pool", "💪 Gym", "🧖 Spa", "⚡ Electric charging station 7kW"],
    cancellationPolicy: "يمكنك إلغاء الحجز قبل 48 ساعة من الوصول.",
    paymentPolicy: "يتم الدفع عند الوصول.",
    minimumAge: 18,
  },
  {
    name: "فندق المرجان",
    city: "الغردقة",
    price: 95,
    rating: 4.4,
    distance: 2.5,
    images: ["/newhotel7.jpg", "/newhotel8.jpg", "/newhotel9.jpg"],
    description: "فندق يطل على الشاطئ مع أنشطة بحرية متنوعة.",
    rooms: 36,
    availableRooms: 8,
    services: ["🅿️ Parking", "🏊 Pool", "💪 Gym", "🐾 Pets", "⚡ Electric charging station 7kW"],
    cancellationPolicy: "يمكنك إلغاء الحجز قبل 48 ساعة من الوصول.",
    paymentPolicy: "يتم الدفع مقدماً.",
    minimumAge: 18,
  },
  {
    name: "فندق اللؤلؤة",
    city: "شرم الشيخ",
    price: 100,
    rating: 4.7,
    distance: 3,
    images: ["/newhotel10.jpg", "/newhotel11.jpg", "/newhotel12.jpg"],
    description: "منتجع فاخر يضم شاطئ خاص ومطاعم عالمية.",
    rooms: 38,
    availableRooms: 9,
    services: ["🅿️ Parking", "🏊 Pool", "💪 Gym", "🧖 Spa", "⚡ Electric charging station 7kW"],
    cancellationPolicy: "يمكنك إلغاء الحجز قبل 48 ساعة من الوصول.",
    paymentPolicy: "يتم الدفع عند الوصول.",
    minimumAge: 18,
  },
  {
    name: "فندق النيل",
    city: "أسوان",
    price: 105,
    rating: 4.0,
    distance: 3.5,
    images: ["/newhotel13.jpg", "/newhotel14.jpg", "/newhotel15.jpg"],
    description: "فندق بإطلالة مباشرة على نهر النيل في أسوان.",
    rooms: 40,
    availableRooms: 10,
    services: ["🅿️ Parking", "🏊 Pool", "💪 Gym", "🐾 Pets", "⚡ Electric charging station 7kW"],
    cancellationPolicy: "يمكنك إلغاء الحجز قبل 48 ساعة من الوصول.",
    paymentPolicy: "يتم الدفع مقدماً.",
    minimumAge: 18,
  },
  {
    name: "فندق الأندلس",
    city: "القاهرة",
    price: 110,
    rating: 4.3,
    distance: 4,
    images: ["/newhotel16.jpg", "/newhotel17.jpg", "/newhotel18.jpg"],
    description: "فندق بتصميم أندلسي فاخر وخدمات عالية الجودة.",
    rooms: 42,
    availableRooms: 11,
    services: ["🅿️ Parking", "🏊 Pool", "💪 Gym", "🧖 Spa", "⚡ Electric charging station 7kW"],
    cancellationPolicy: "يمكنك إلغاء الحجز قبل 48 ساعة من الوصول.",
    paymentPolicy: "يتم الدفع عند الوصول.",
    minimumAge: 18,
  },
  {
    name: "فندق الرمال الذهبية",
    city: "الإسكندرية",
    price: 115,
    rating: 4.6,
    distance: 4.5,
    images: ["/newhotel19.jpg", "/newhotel20.jpg", "/newhotel21.jpg"],
    description: "فندق يطل على شاطئ خاص في الإسكندرية.",
    rooms: 44,
    availableRooms: 12,
    services: ["🅿️ Parking", "🏊 Pool", "💪 Gym", "🐾 Pets", "⚡ Electric charging station 7kW"],
    cancellationPolicy: "يمكنك إلغاء الحجز قبل 48 ساعة من الوصول.",
    paymentPolicy: "يتم الدفع مقدماً.",
    minimumAge: 18,
  },
//   {
//     name: "فندق المرج الأخضر",
//     city: "الغردقة",
//     price: 120,
//     rating: 4.2,
//     distance: 5,
//     images: ["/newhotel22.jpg", "/newhotel23.jpg", "/newhotel24.jpg"],
//     description: "منتجع يقدم أجواء هادئة وخدمات سبا متكاملة.",
//     rooms: 46,
//     availableRooms: 13,
//     services: ["🅿️ Parking", "🏊 Pool", "💪 Gym", "🧖 Spa", "⚡ Electric charging station 7kW"],
//     cancellationPolicy: "يمكنك إلغاء الحجز قبل 48 ساعة من الوصول.",
//     paymentPolicy: "يتم الدفع عند الوصول.",
//     minimumAge: 18,
//   },
//   {
//     name: "فندق الكريستال",
//     city: "شرم الشيخ",
//     price: 125,
//     rating: 4.8,
//     distance: 5.5,
//     images: ["/newhotel25.jpg", "/newhotel26.jpg", "/newhotel27.jpg"],
//     description: "فندق فاخر يضم غرف مطلة على البحر الأحمر.",
//     rooms: 48,
//     availableRooms: 14,
//     services: ["🅿️ Parking", "🏊 Pool", "💪 Gym", "🐾 Pets", "⚡ Electric charging station 7kW"],
//     cancellationPolicy: "يمكنك إلغاء الحجز قبل 48 ساعة من الوصول.",
//     paymentPolicy: "يتم الدفع مقدماً.",
//     minimumAge: 18,
//   },
//   {
//     name: "فندق الفيوم",
//     city: "أسوان",
//     price: 130,
//     rating: 4.1,
//     distance: 6,
//     images: ["/newhotel28.jpg", "/newhotel29.jpg", "/newhotel30.jpg"],
//     description: "فندق هادئ بالقرب من المعابد الأثرية.",
//     rooms: 50,
//     availableRooms: 15,
//     services: ["🅿️ Parking", "🏊 Pool", "💪 Gym", "🧖 Spa", "⚡ Electric charging station 7kW"],
//     cancellationPolicy: "يمكنك إلغاء الحجز قبل 48 ساعة من الوصول.",
//     paymentPolicy: "يتم الدفع عند الوصول.",
//     minimumAge: 18,
//   },
//   {
//     name: "فندق الشمس",
//     city: "القاهرة",
//     price: 135,
//     rating: 4.5,
//     distance: 6.5,
//     images: ["/newhotel31.jpg", "/newhotel32.jpg", "/newhotel33.jpg"],
//     description: "فندق يقدم تجربة سياحية عائلية في قلب العاصمة.",
//     rooms: 52,
//     availableRooms: 16,
//     services: ["🅿️ Parking", "🏊 Pool", "💪 Gym", "🐾 Pets", "⚡ Electric charging station 7kW"],
//     cancellationPolicy: "يمكنك إلغاء الحجز قبل 48 ساعة من الوصول.",
//     paymentPolicy: "يتم الدفع مقدماً.",
//     minimumAge: 18,
//   },
//   {
//     name: "فندق البحر الأبيض",
//     city: "الإسكندرية",
//     price: 140,
//     rating: 4.9,
//     distance: 7,
//     images: ["/newhotel34.jpg", "/newhotel35.jpg", "/newhotel36.jpg"],
//     description: "فندق بإطلالة بانورامية على البحر الأبيض المتوسط.",
//     rooms: 54,
//     availableRooms: 17,
//     services: ["🅿️ Parking", "🏊 Pool", "💪 Gym", "🧖 Spa", "⚡ Electric charging station 7kW"],
//     cancellationPolicy: "يمكنك إلغاء الحجز قبل 48 ساعة من الوصول.",
//     paymentPolicy: "يتم الدفع عند الوصول.",
//     minimumAge: 18,
//   },
//   {
//     name: "فندق الواحة الخضراء",
//     city: "الغردقة",
//     price: 145,
//     rating: 4.3,
//     distance: 7.5,
//     images: ["/newhotel37.jpg", "/newhotel38.jpg", "/newhotel39.jpg"],
//     description: "فندق محاط بحدائق خضراء ومساحات استرخاء.",
//     rooms: 56,
//     availableRooms: 18,
//     services: ["🅿️ Parking", "🏊 Pool", "💪 Gym", "🐾 Pets", "⚡ Electric charging station 7kW"],
//     cancellationPolicy: "يمكنك إلغاء الحجز قبل 48 ساعة من الوصول.",
//     paymentPolicy: "يتم الدفع مقدماً.",
//     minimumAge: 18,
//   },
//   {
//     name: "فندق المرجان الأزرق",
//     city: "شرم الشيخ",
//     price: 150,
//     rating: 5.0,
//     distance: 8,
//     images: ["/newhotel40.jpg", "/newhotel41.jpg", "/newhotel42.jpg"],
//     description: "منتجع شامل يقدم أنشطة بحرية وسهرات ترفيهية.",
//     rooms: 58,
//     availableRooms: 19,
//     services: ["🅿️ Parking", "🏊 Pool", "💪 Gym", "🧖 Spa", "⚡ Electric charging station 7kW"],
//     cancellationPolicy: "يمكنك إلغاء الحجز قبل 48 ساعة من الوصول.",
//     paymentPolicy: "يتم الدفع عند الوصول.",
//     minimumAge: 18,
//   },
//   {
//     name: "فندق الفجر",
//     city: "أسوان",
//     price: 155,
//     rating: 4.6,
//     distance: 8.5,
//     images: ["/newhotel43.jpg", "/newhotel44.jpg", "/newhotel45.jpg"],
//     description: "فندق أنيق بالقرب من المعالم التاريخية.",
//     rooms: 60,
//     availableRooms: 20,
//     services: ["🅿️ Parking", "🏊 Pool", "💪 Gym", "🐾 Pets", "⚡ Electric charging station 7kW"],
//     cancellationPolicy: "يمكنك إلغاء الحجز قبل 48 ساعة من الوصول.",
//     paymentPolicy: "يتم الدفع مقدماً.",
//     minimumAge: 18,
//   }
];

export const seedHotels = async () => {
  try {
    // امسح كل البيانات القديمة
    await Hotel.deleteMany({});

    // أضف البيانات الجديدة
    await Hotel.insertMany(hotels);

    console.log("✅ Hotels seeded successfully (old data cleared)");
  } catch (error) {
    console.error("❌ Error seeding hotels:", error);
  }
};


